name: Deploy Multiple React Projects

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # 16 또는 현재 LTS 버전 사용

    - name: Install dependencies and build nnn99
      working-directory: ./nnn99
      run: |
        npm install
        npm run build

    - name: Install dependencies and build todo
      working-directory: ./todo
      run: |
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./todo/build # `todo` 프로젝트만 배포
